dist: trusty
sudo: false
language: node_js
node_js:
  - 'node'

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: 'wpocanvas'

script:
  - npm install
  - npm run-script build:prod
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAW5B3DWY7XATC7I35
  secret_access_key: '$SECRET_ACCESS_KEY'
  bucket: audit-tool-frontend
  local-dir: dist/angular-boiler-plate
  acl: public_read
  on:
    repo: WPOCanvas/Audit-Tool-Frontend
    branches:
      only:
        - master
